# Model Parameters
sh_degree: 3
init_points: 131_072
final_points: 1_097_152
activation_scale: 1
device: cuda
max_frames: 300
np: 3

# Pipeline Parameters
iterations: 20_000
densify_from: 2_000
densify_until: 11_000
densify_factor: 1.15
white_background: true
quantile_weight: 1e-4
viewer: false                          # Flag to use viewer
debug: false                           # Flag to not use tensorboard

# Optimization Parameters
points_lr_init: 2e-4
points_lr_final: 5e-6
deform_lr_init: 4e-4 # 1.75 point
deform_lr_final: 9e-6
density_lr_init: 1e-1 
density_lr_final: 1e-2
attributes_lr_init: 5e-3
attributes_lr_final: 5e-4
temporal_center_lr_init: 5e-4  # duration 0.03 center 0.0001
temporal_center_lr_final: 5e-5
temporal_duration_lr_init: 3e-2  # duration 0.03 center 0.0001
temporal_duration_lr_final: 3e-3
temporal_attr_scale_lr_init: 3e-4 
temporal_attr_scale_lr_final: 3e-5
sh_factor: 0.1
freeze_points: 18_000                  # Points are frozen after this cycle

# Dataset Parameters
dataset: "n3v"
data_path: "data/N3V"
scene: "coffee_smal"
patch_based: false
downsample: [4, 2]                     # Image downsample factors
downsample_iterations: [0, 5000]
